name: Build and Deploy Discord Bot

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'

      - name: Build binary
        run: |
          go build -o bot .

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Stop Bot on EC2
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.IP }} << 'EOF'
            sudo systemctl stop discord-bot
          EOF

      - name: Copy files via SSH
        run: |
          scp -o StrictHostKeyChecking=no bot ${{ secrets.USERNAME }}@${{ secrets.IP }}:~/bot
          scp -o StrictHostKeyChecking=no -r historical_data.json ${{ secrets.USERNAME }}@${{ secrets.IP }}:~/

      - name: Restart Bot on EC2
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.IP }} << 'EOF'
            sudo systemctl start discord-bot
          EOF
